PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX fao: <http://www.fao.org/countryprofiles/geoinfo/geopolitical/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>


CONSTRUCT {
  <http://aims.fao.org/aos/agrovoc/c_10176> 
    rdfs:label ?label ; 
    dcterms:identifier ?parent_id ;
    skos:narrower ?child_concept .
  
  ?child_concept 
    dcterms:identifier ?child_id ;
    ?child_predicate ?child_object .

} WHERE {
  {
    GRAPH <http://linked-development.org/graph/r4d> {

      <http://aims.fao.org/aos/agrovoc/c_10176> 
           a skos:Concept ;
           skos:prefLabel ?label .

      BIND(replace(str(<http://aims.fao.org/aos/agrovoc/c_10176>), "http://aims.fao.org/aos/agrovoc/", '') AS ?parent_id)

      OPTIONAL {
        <http://aims.fao.org/aos/agrovoc/c_10176> skos:narrower ?child_concept .
        BIND(replace(str(?child_concept), "http://aims.fao.org/aos/agrovoc/", '') AS ?child_id) .
        ?child_concept ?child_predicate ?child_object ;
        FILTER NOT EXISTS { ?child_concept skos:narrower ?something }
      }
    }
  } UNION {
    GRAPH <http://linked-development.org/graph/eldis> {
      <http://linked-development.org/eldis/themes/C782/> 
        a skos:Concept ;
        rdfs:label ?label ;
        dcterms:identifier ?parent_id .
      
      OPTIONAL { 
        <http://linked-development.org/eldis/themes/C782/> skos:narrower ?child_concept .

        ?child_concept 
          dcterms:identifier ?child_id ;
          ?child_predicate ?child_object .

        FILTER NOT EXISTS { ?child_concept skos:narrower ?something }
      }
    }
  }
}
